import { useState, useEffect } from 'react';
import { api } from '@/services/api';

interface UniversityStats {
  totalApplications: number;
  pendingApplications: number;
  acceptedApplications: number;
  rejectedApplications: number;
  reviewingApplications: number;
}

export default function UniversityDashboard() {
  const [applications, setApplications] = useState([]);
  const [stats, setStats] = useState<UniversityStats>({
    totalApplications: 0,
    pendingApplications: 0,
    acceptedApplications: 0,
    rejectedApplications: 0,
    reviewingApplications: 0
  });
  const [loading, setLoading] = useState(true);
  const [selectedTab, setSelectedTab] = useState('all');

  useEffect(() => {
    fetchApplications();
  }, []);

  const fetchApplications = async () => {
    try {
      const response = await fetch('http://localhost:8081/api/applications/university/1');
      const data = await response.json();
      setApplications(data);
      
      const total = data.length;
      const pending = data.filter(a => a.status === 'PENDING').length;
      const accepted = data.filter(a => a.status === 'ACCEPTED').length;
      const rejected = data.filter(a => a.status === 'REJECTED').length;
      const reviewing = data.filter(a => a.status === 'REVIEWING').length;
      
      setStats({ 
        totalApplications: total, 
        pendingApplications: pending, 
        acceptedApplications: accepted, 
        rejectedApplications: rejected,
        reviewingApplications: reviewing 
      });
    } catch (error) {
      console.error('Error:', error);
    } finally {
      setLoading(false);
    }
  };

  const updateStatus = async (appId: number, newStatus: string) => {
    await fetch(`http://localhost:8081/api/applications/${appId}/status`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ status: newStatus })
    });
    fetchApplications();
  };

  // ============ REPORT DOWNLOAD FUNCTION ============
  const generateSummaryReport = () => {
    // Calculate acceptance rate
    const acceptanceRate = stats.totalApplications > 0 
      ? ((stats.acceptedApplications / stats.totalApplications) * 100).toFixed(2) 
      : '0';
    
    // Group applications by status
    const appsByStatus: Record<string, number> = {};
    applications.forEach((app: any) => {
      appsByStatus[app.status] = (appsByStatus[app.status] || 0) + 1;
    });
    
    const reportText = `
╔════════════════════════════════════════════════════════════════╗
║              STUDYADVISOR - APPLICATION SUMMARY REPORT         ║
║                      Generated by University Admin             ║
╚════════════════════════════════════════════════════════════════╝

📅 REPORT DETAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Generated Date: ${new Date().toLocaleString()}
  Report ID: SA-REP-${Date.now()}
  Generated By: University Admin (University ID: 1)

📊 SUMMARY STATISTICS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Total Applications Received:  ${stats.totalApplications}
  ├─ Pending Review:           ${stats.pendingApplications}
  ├─ Under Review:             ${stats.reviewingApplications}
  ├─ Accepted:                 ${stats.acceptedApplications}
  └─ Rejected:                 ${stats.rejectedApplications}

📈 ACCEPTANCE RATE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Overall Acceptance Rate:     ${acceptanceRate}%
  Rejection Rate:              ${((stats.rejectedApplications / stats.totalApplications) * 100).toFixed(2)}%

📋 STATUS BREAKDOWN
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${Object.entries(appsByStatus).map(([status, count]) => 
  `  ${status.padEnd(15)} : ${count} application(s)`
).join('\n')}

📝 RECENT APPLICATIONS (Last 5)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${applications.slice(0, 5).map((app: any, i: number) => 
  `  ${i+1}. ${app.studentName} - ${app.program?.name || 'N/A'} - ${app.status}`
).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  End of Report - StudyAdvisor Pakistan
  This is an automatically generated report.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    `;
    
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Application_Summary_Report_${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    
    alert('✅ Summary report downloaded successfully!');
  };

  // ============ CSV EXPORT FUNCTION ============
  const exportToCSV = () => {
    if (applications.length === 0) {
      alert('No applications to export');
      return;
    }
    
    const headers = ['ID', 'Student Name', 'Email', 'Phone', 'Qualification', 'Program', 'Status', 'Application Date'];
    const rows = applications.map((app: any) => [
      app.id,
      app.studentName,
      app.studentEmail,
      app.studentPhone || 'N/A',
      app.academicQualification || 'N/A',
      app.program?.name || 'N/A',
      app.status,
      new Date(app.applicationDate).toLocaleDateString()
    ]);
    
    const csvContent = [headers, ...rows].map(row => row.join(',')).join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Applications_Export_${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    
    alert('✅ CSV file downloaded successfully!');
  };

  const filteredApps = selectedTab === 'all' ? applications : 
                        applications.filter((a: any) => a.status === selectedTab.toUpperCase());

  if (loading) return <div className="p-8 text-center">Loading dashboard...</div>;

  return (
    <div className="min-h-screen bg-gray-50 pt-20">
      <div className="container mx-auto px-4 py-8">
        
        {/* Header with Report Buttons */}
        <div className="flex justify-between items-center mb-8">
          <h1 className="text-3xl font-bold text-[#1E3A8F]">University Admission Dashboard</h1>
          <div className="flex gap-3">
            {/* CSV Export Button */}
            <button 
              onClick={exportToCSV}
              className="bg-green-600 text-white px-4 py-2 rounded-lg text-sm hover:bg-green-700 flex items-center gap-2"
            >
              📊 Export to CSV
            </button>
            {/* Summary Report Button */}
            <button 
              onClick={generateSummaryReport}
              className="bg-purple-600 text-white px-4 py-2 rounded-lg text-sm hover:bg-purple-700 flex items-center gap-2"
            >
              📄 Download Summary Report
            </button>
          </div>
        </div>
        
        {/* Statistics Cards */}
        <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-8">
          <div className="bg-white rounded-lg shadow p-4 text-center border-l-4 border-blue-500">
            <div className="text-2xl font-bold text-blue-600">{stats.totalApplications}</div>
            <div className="text-sm text-gray-500">Total Applications</div>
          </div>
          <div className="bg-white rounded-lg shadow p-4 text-center border-l-4 border-yellow-500">
            <div className="text-2xl font-bold text-yellow-600">{stats.pendingApplications}</div>
            <div className="text-sm text-gray-500">Pending Review</div>
          </div>
          <div className="bg-white rounded-lg shadow p-4 text-center border-l-4 border-purple-500">
            <div className="text-2xl font-bold text-purple-600">{stats.reviewingApplications}</div>
            <div className="text-sm text-gray-500">Under Review</div>
          </div>
          <div className="bg-white rounded-lg shadow p-4 text-center border-l-4 border-green-500">
            <div className="text-2xl font-bold text-green-600">{stats.acceptedApplications}</div>
            <div className="text-sm text-gray-500">Accepted</div>
          </div>
          <div className="bg-white rounded-lg shadow p-4 text-center border-l-4 border-red-500">
            <div className="text-2xl font-bold text-red-600">{stats.rejectedApplications}</div>
            <div className="text-sm text-gray-500">Rejected</div>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex gap-2 mb-6 border-b">
          <button onClick={() => setSelectedTab('all')} className={`px-4 py-2 ${selectedTab === 'all' ? 'border-b-2 border-[#00C7B1] text-[#00C7B1]' : 'text-gray-500'}`}>All ({stats.totalApplications})</button>
          <button onClick={() => setSelectedTab('pending')} className={`px-4 py-2 ${selectedTab === 'pending' ? 'border-b-2 border-[#00C7B1] text-[#00C7B1]' : 'text-gray-500'}`}>Pending ({stats.pendingApplications})</button>
          <button onClick={() => setSelectedTab('reviewing')} className={`px-4 py-2 ${selectedTab === 'reviewing' ? 'border-b-2 border-[#00C7B1] text-[#00C7B1]' : 'text-gray-500'}`}>Reviewing ({stats.reviewingApplications})</button>
          <button onClick={() => setSelectedTab('accepted')} className={`px-4 py-2 ${selectedTab === 'accepted' ? 'border-b-2 border-[#00C7B1] text-[#00C7B1]' : 'text-gray-500'}`}>Accepted ({stats.acceptedApplications})</button>
          <button onClick={() => setSelectedTab('rejected')} className={`px-4 py-2 ${selectedTab === 'rejected' ? 'border-b-2 border-[#00C7B1] text-[#00C7B1]' : 'text-gray-500'}`}>Rejected ({stats.rejectedApplications})</button>
        </div>

        {/* Applications Table */}
        <div className="bg-white rounded-lg shadow overflow-hidden">
          <table className="w-full">
            <thead className="bg-[#1E3A8F] text-white">
              <tr>
                <th className="p-3 text-left">Student Name</th>
                <th className="p-3 text-left">Program</th>
                <th className="p-3 text-left">Qualifications</th>
                <th className="p-3 text-left">Applied Date</th>
                <th className="p-3 text-left">Status</th>
                <th className="p-3 text-left">Actions</th>
              </tr>
            </thead>
            <tbody>
              {filteredApps.map((app: any) => (
                <tr key={app.id} className="border-b hover:bg-gray-50">
                  <td className="p-3">
                    <div className="font-medium">{app.studentName}</div>
                    <div className="text-xs text-gray-500">{app.studentEmail}</div>
                  </td>
                  <td className="p-3">{app.program?.name || 'N/A'}</td>
                  <td className="p-3">{app.academicQualification || 'N/A'}</td>
                  <td className="p-3">{new Date(app.applicationDate).toLocaleDateString()}</td>
                  <td className="p-3">
                    <span className={`px-2 py-1 rounded text-xs ${
                      app.status === 'PENDING' ? 'bg-yellow-100 text-yellow-800' :
                      app.status === 'REVIEWING' ? 'bg-blue-100 text-blue-800' :
                      app.status === 'ACCEPTED' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'
                    }`}>
                      {app.status}
                    </span>
                  </td>
                  <td className="p-3">
                    <div className="flex gap-2">
                      {app.status === 'PENDING' && (
                        <button onClick={() => updateStatus(app.id, 'REVIEWING')} className="bg-blue-500 text-white px-2 py-1 rounded text-xs">Review</button>
                      )}
                      {app.status === 'REVIEWING' && (
                        <>
                          <button onClick={() => updateStatus(app.id, 'ACCEPTED')} className="bg-green-500 text-white px-2 py-1 rounded text-xs">Accept</button>
                          <button onClick={() => updateStatus(app.id, 'REJECTED')} className="bg-red-500 text-white px-2 py-1 rounded text-xs">Reject</button>
                        </>
                      )}
                      {(app.status === 'PENDING' || app.status === 'REVIEWING') && (
                        <>
                          <button onClick={() => updateStatus(app.id, 'ACCEPTED')} className="bg-green-500 text-white px-2 py-1 rounded text-xs">Accept</button>
                          <button onClick={() => updateStatus(app.id, 'REJECTED')} className="bg-red-500 text-white px-2 py-1 rounded text-xs">Reject</button>
                        </>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          {filteredApps.length === 0 && (
            <div className="text-center py-8 text-gray-500">No applications found</div>
          )}
        </div>

        {/* Application Trends Chart */}
        <div className="bg-white rounded-lg shadow p-6 mt-8">
          <div className="flex justify-between items-center mb-4">
            <h2 className="text-xl font-bold text-[#1E3A8F]">Application Trends</h2>
            <span className="text-xs text-gray-400">Demo Data</span>
          </div>
          <div className="h-64 flex items-end gap-4">
            {['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'].map((month, i) => (
              <div key={month} className="flex-1 text-center">
                <div className="bg-[#00C7B1] rounded-t-lg transition-all duration-500 hover:bg-[#1E3A8F] cursor-pointer"
                     style={{ height: `${Math.random() * 150 + 50}px` }}>
                </div>
                <div className="text-sm text-gray-500 mt-2">{month}</div>
                <div className="text-xs font-semibold text-[#1E3A8F]">{Math.floor(Math.random() * 30) + 5}</div>
              </div>
            ))}
          </div>
          <p className="text-sm text-gray-400 text-center mt-4">📊 Application volume by month (based on historical data)</p>
        </div>
      </div>
    </div>
  );
}